events {
    worker_connections 1024;
}

http {
    client_max_body_size 2048M;

    upstream frontend     { server frontend:3000; }
    upstream auth         { server auth-service:3001; }
    upstream upload       { server upload-service:3002; }
    upstream video        { server video-service:3003; }
    upstream chat         { server chat-service:4004; }

    server {
        listen 80;
        server_name _;

        location /api/auth/ {
            proxy_pass http://auth/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/upload/ {
            proxy_pass http://upload/api/upload/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/videos/ {
            proxy_pass http://video/api/videos/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/chat {
            proxy_pass http://chat/api/chat;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/search {
            proxy_pass http://chat/api/search;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}